### ISSUE TITLE
Realize auto hide scrollbar

### ISSUE THREAD

**Issue by gerainlotZS** [xobotyi/react-scrollbars-custom#131]
I want realize auto hide when scrollbar not used
I may can't use removeTracksWhenNotUsed or permanentTracks
How to use these attributes

**Comment by xobotyi** [comment]
It us described in docs =/

**Comment by gerainlotZS** [comment]
but not removeTracksWhenNotUsed or permanentTracks worked
`<ScrollBar 
removeTrackYWhenNotUsed
              permanentTrackY={false}
              onUpdate={handleScrollBarScroll}
            />`

**Comment by xobotyi** [comment]
If permanentTrack is true scrollbars will be shown even if there is no scroll possibility.
removeTrackWhenNotUsed will prevent the track rendering if there is no scroll possibility.

This library has no autohide implementation due to only small amount of developers need that feature and there is no sense to increase bundle size for most part of developers who don't need it.

**Comment by xobotyi** [comment]
Here you can find the implementation: #43

**Comment by gerainlotZS** [comment]
Thanks, the product need that feature, so I add an auto-hide implementation in my project, Thank a lot!
