### ISSUE TITLE
Is there a way to make this work with max-height?

### ISSUE THREAD

**Issue by StJohn3D** [xobotyi/react-scrollbars-custom#21]
I don't want to have a fixed height, just a max-height. My goal is to create a dropdown list selector which is only as big as it needs to be (depending on how many items it has). But then after reaching a certain max height will display scrollbars. I see this component is already smart enough to only show scrollbars when it needs to. But I don't know how to get it to work with a height based on it's children.

Bonus: Would be cool if it were possible to make is scroll after a certain number of children.

E.g. `maxHeight={350}` or `numChildrenBeforeScroll={5}` using whichever comes first.

**Comment by xobotyi** [comment]
Had that issue this week too, and exactly with select too=). 
Due to content element is absolutely positioned it can't stretch parent, so we have to do it wih JS.

I've made an onScroll handler and assigning scrollHeight parameter to the dropdown element. (https://github.com/xobotyi/react-ez-select/blob/33ba72a064478806cf4793fca8bb5331c1499bfe/src/index.js#L526)
And making same stuff each dropdown opening (https://github.com/xobotyi/react-ez-select/blob/33ba72a064478806cf4793fca8bb5331c1499bfe/src/index.js#L493).

Atually i'm not sure that this behaviout should be out of the box.

**Comment by xobotyi** [comment]
>Bonus: Would be cool if it were possible to make is scroll after a certain number of children.

Don't understand what for. It is one more extra check, and 4ex: if elements will not overfow the height and you'll set that parametr you;ll have tha scrollbars without srolling possibility.

**Comment by StJohn3D** [comment]
Thanks for the reply. I changed the wording to hopefully make that bonus question make more sense. I was thinking that in cases where you don't know or care about the height, you just want to show a maximum of like 5 options and show a scrollbar in the event there are more than that. But if you used both than it could be which-ever comes first.

Anyway, I tried to follow your code example with no success. For now I think I'm just going to try and implement the functionality myself. I've stared this repo though so if you ever add a more convenient way to handle max-height I'd love to check it out.

**Comment by xobotyi** [comment]
@StJohn3D can I see the code? Just wonder why it did not helped in your case.

**Comment by StJohn3D** [comment]
@xobotyi 
Well I got it to work just now, and I think in an even simpler way.

The code looks like this:

```tsx
export class Scrollable extends Component<IScrollableProps> {
  contentRef: RefObject<HTMLDivElement> = React.createRef()
  clientHeight: number = 1

  constructor(props: IScrollableProps) {
    super(props)
  }

  componentDidMount() {
    const content = this.contentRef.current
    this.clientHeight = content && content.clientHeight || 1
  }

  render() {
    const { maxHeight, children, className } = this.props

    return (<Scrollbar style={{ width: '100%', height: this.clientHeight, maxHeight: maxHeight }} >
      <div className={classNames(scrollable-content, className)} ref={this.contentRef}>
        {children}
      </div>
    </Scrollbar>)
  }
}
```

With this height is always the correct length and if my content goes over maxHeight, it'll show the scroll bar. I'm really happy I can use your component because trying to implement this myself has been time consuming. I got close but got stuck trying to figure out how to incorporate RAF for smoother scrolling. Then I decided to give this just one more shot and it finally worked!

Thanks for all your hard work on this component - it's really good. And now for anyone else arriving here with my same question, there's the code example for how to do it. Basically wrap your content in something and keep a ref to it. The get the clientHeight off your content ref and plug that into the height value for Scrollbar.

**Comment by ZuchaoWang** [comment]
@xobotyi 
Very good library! Many thanks!

@StJohn3D 
Very good example to support autoHeight. Saved me hours of hacking!

Actually it might have a tiny flaw. This is because autoHeight function is supported smartly via `this.clientHeight`, which is value `1` when `this.render` is first called. Although later it will be updated correctly in `this.componentDidMount`, there's no guarantee that a `this.render` will be followed to use the correct `this.clientHeight`. So the height of the scrollbar content might still be the initial value `1`. 

I would suggest to use `this.state.clientHeight`, so that it's guaranteed to have a re-render after the correct `clientHeight` is generated. For more complex dropdown scrollbar cases, where `this.children` can update, `this.state.clientHeight` might also need to be updated in `this.componentDidUpdate`.

**Comment by StJohn3D** [comment]
@ZuchaoWang Good point! So far that hasn't bit me, although I updated the example to initialize to 0. So you're suggesting I move clientHeight to state, and update in componentDidUpdate to ensure it's always current? Thanks!

**Comment by xobotyi** [comment]
@ZuchaoWang @StJohn3D 
I've implemented sizes translation in v3 (on dev-master now). Now i'm writing tests, docs and etc. release is planned for next week i think. 
If you wish to try - you can pull it [here](https://github.com/xobotyi/react-scrollbars-custom/tree/dev-master).

**Comment by ZuchaoWang** [comment]
> @ZuchaoWang Good point! So far that hasn't bit me, although I updated the example to initialize to 0. So you're suggesting I move clientHeight to state, and update in componentDidUpdate to ensure it's always current? Thanks!

Yes, that's what I suggested. You're welcome!
