### ISSUE TITLE
 How to set thumb size?

### ISSUE THREAD

**Issue by sinevitch** [xobotyi/react-scrollbars-custom#40]
![image](https://user-images.githubusercontent.com/35930695/50972311-5f4efb00-14f7-11e9-9a98-2082e9059a78.png)

Why not set the size of the thumb?

**Comment by xobotyi** [comment]
Because your content does not overflow, so there is no scrol possibility, so there is no thumb (if you'll remove the permanentTrackX there even will be no track).
Change the contents `display` or add `flex-shrink:0` to every paragraph.

P.s. attaching code as a screenshot is... idk how even to name it..
