### ISSUE TITLE
Enabling maximalThumbsSize prop

### ISSUE THREAD

**Issue by gamegee** [xobotyi/react-scrollbars-custom#44]
**Do you want to request a _feature_ or report a _bug_?**
Request a feature

**What is the current behavior?**
The API does not provide a way to pass maximalThumbsSize as props.
It could be really helpful for UI reasons (sometimes the size of your scrollbar almost fit its track container size)

**What is the expected behavior?**
Provide the maximalThumbsSize prop. Given that maximalThumbsSize, the scrollbar should change the way the position is computed (I guess).

**Comment by xobotyi** [comment]
You can set the paddings for track and maximal thumb size will be respective for them (paddings).

**Comment by gamegee** [comment]
Ok but if we have a vertical scrollbar and I set paddings (top and bottom), my thumb would not be able to reach the top and the bottom.

In this example I'm on the top of the scrolling content:
![image](https://user-images.githubusercontent.com/15988848/53626594-6a283100-3c06-11e9-9a6c-dbc2872acef4.png)

**Comment by xobotyi** [comment]
Thats true.
I just can't imagine situation when you have to set max size. Thumb size is intuitive represents how much content you see now and how much still "out there". If to set the maximal size it will 1) break that representation 2) slow down the lib a bit due to extra calculations for each scrolling step =\
not sure if it is necessary.
Anyways i'm bisy with package rework yet, if anywone will vote for that feeature too i'll add it somewhere around 3.4.x-3.5.x versions.

**Comment by gamegee** [comment]
Here is an example of something I want to avoid in my UI:

![image](https://user-images.githubusercontent.com/15988848/53628234-c55c2280-3c0a-11e9-9ae8-574cc8d85296.png)

But ofc I get your point. I could also do a pull request if you need - leaving the default computation when maximalThumbsSize is not set.

**Comment by xobotyi** [comment]
@gamegee no sence, cause lib will be rewritten from scratch onto TS since 3.2

**Comment by xobotyi** [comment]
Feature added in 4.0.0-aplha
