### ISSUE TITLE
Scroll container doesn't shrink when contents shrink

### ISSUE THREAD

**Issue by alexpaxton** [xobotyi/react-scrollbars-custom#52]
Using `4.0.0-alpha.12`
This is roughly what I am doing:

```
<Scrollbar
  translateContentSizesToHolder={true}
  style={{
    maxWidth: '100%',
    maxHeight: '300px',
  }}
  noScrollX={true}
>
  // test div
  <div style={{width: '100%', height: '300px'}} />
</Scrollbar>
```

Initially everything looks fine, but if I change the height of the test div to be `100px` (for example) the vertical scrollbar disappears as expected but the scroll container retains a `300px` height and does not shrink to match the size of its children.

When I inspect what's happening in the browser I notice that the scroll container has a height of `305px`, which seems to create a little gap at the bottom. Not sure where that `5px` extra is coming from

**Comment by xobotyi** [comment]
I know about this problem and actually dont know how to fix it correctly atm.

In general it translate `scrollHeight`/`scrollWidth` values of content element to the holder element. It works when content sizes increases, but doesn't when it decreases.  
Because `scrollHeight` can't be less than `clientHeight`.

Ideally, placing the relatively positioned div inside the content element which will hold the scrollbar's content, with no margins and padding, should solve the problem, cause it'll be able to grow and shrink in spite of scrollbar elements.  
But not sure that it will be an optimal solution (it'll slow down scrollbars update process and add an extra div).

**Comment by xobotyi** [comment]
About the gap - what browser and OS do you use?

**Comment by alexpaxton** [comment]
I am using Chrome / Mac OSX

**Comment by rvillalba-novetta** [comment]
I'm currently being hit by the same size decrease issue.

**Comment by xobotyi** [comment]
@alexpaxton most likely `alpha.17` should resolve tha gap problem, but i'm not sure.  
So check it please and poke me on any results.
